import React from 'react';

const ML: React.FC = () => {
  return (
    <div className="min-h-screen bg-gradient-to-b from-white to-blue-50 p-6">
      <div className="max-w-5xl mx-auto">
        <h1 className="text-3xl font-bold mb-6 text-blue-800">Machine Learning Approach</h1>
        
        <div className="bg-white p-6 rounded-xl shadow-lg mb-8">
          <h2 className="text-xl font-semibold mb-4 text-blue-700">XGBoost Model for Energy Prediction</h2>
          
          <p className="mb-4">
            For predicting solar energy generation, we implemented an XGBoost regression model due to its 
            effectiveness with tabular data and ability to handle non-linear relationships. This gradient 
            boosting algorithm has shown excellent performance in capturing complex patterns between 
            weather variables and energy output.
          </p>

          <h3 className="text-lg font-semibold mb-2 text-blue-600">Input Features</h3>
          <div className="overflow-x-auto mb-4">
            <table className="min-w-full border-collapse mb-4">
              <thead>
                <tr className="bg-blue-100">
                  <th className="border border-blue-200 px-4 py-2 text-left">Feature</th>
                  <th className="border border-blue-200 px-4 py-2 text-left">Description</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="border border-blue-200 px-4 py-2">Month, Day, Hour</td>
                  <td className="border border-blue-200 px-4 py-2">Temporal features for seasonal patterns</td>
                </tr>
                <tr>
                  <td className="border border-blue-200 px-4 py-2">globalHorizontalIrradiance</td>
                  <td className="border border-blue-200 px-4 py-2">Solar radiation reaching the earth (key predictor)</td>
                </tr>
                <tr>
                  <td className="border border-blue-200 px-4 py-2">pressureMeanSeaLevel</td>
                  <td className="border border-blue-200 px-4 py-2">Atmospheric pressure</td>
                </tr>
                <tr>
                  <td className="border border-blue-200 px-4 py-2">temperature</td>
                  <td className="border border-blue-200 px-4 py-2">Ambient temperature (affects solar panel efficiency)</td>
                </tr>
                <tr>
                  <td className="border border-blue-200 px-4 py-2">uvIndex</td>
                  <td className="border border-blue-200 px-4 py-2">UV radiation intensity</td>
                </tr>
              </tbody>
            </table>
          </div>

          <h3 className="text-lg font-semibold mb-2 text-blue-600">Target Variables</h3>
          <ul className="list-disc pl-6 mb-4">
            <li>DC Array Output (W): Raw power generated by solar panels</li>
            <li>AC System Output (W): Converted power after inversion (what's actually usable)</li>
          </ul>

          <h3 className="text-lg font-semibold mb-2 text-blue-600">Methodology</h3>
          <ol className="list-decimal pl-6 mb-4">
            <li className="mb-1">Data preprocessing: Handled missing values and normalized features</li>
            <li className="mb-1">Feature engineering: Created time-based features and weather-related interactions</li>
            <li className="mb-1">Train-test split: 80% training, 20% testing data</li>
            <li className="mb-1">Model training: XGBoost with hyperparameter tuning via grid search</li>
            <li className="mb-1">Evaluation: Using RMSE (Root Mean Square Error) and R² metrics</li>
          </ol>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-lg mb-8">
          <h2 className="text-xl font-semibold mb-4 text-blue-700">Model Performance</h2>
          
          <div className="mb-4">
            <h3 className="text-lg font-semibold mb-2 text-blue-600">Results</h3>
            <table className="min-w-full border-collapse mb-6">
              <thead>
                <tr className="bg-blue-100">
                  <th className="border border-blue-200 px-4 py-2">Metric</th>
                  <th className="border border-blue-200 px-4 py-2">AC Prediction</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td className="border border-blue-200 px-4 py-2">RMSE</td>
                  <td className="border border-blue-200 px-4 py-2">299.16 W</td>
                </tr>
                <tr>
                  <td className="border border-blue-200 px-4 py-2">R² Score</td>
                  <td className="border border-blue-200 px-4 py-2">0.9083</td>
                </tr>
              </tbody>
            </table>
          </div>

          <div className="flex flex-col items-center mb-6">
            <h3 className="text-lg font-semibold mb-4 text-blue-600">Predicted vs Actual Energy Generation</h3>
            <div className="w-full max-w-3xl bg-gray-100 rounded-lg p-2 text-center mb-2">
              {/* Replace with your actual image path */}
              <div className="relative h-80 w-full">
                <img 
                  src="ml.png" 
                  alt="Prediction Results Plot" 
                // //   layout="fill"
                //   objectFit="contain"
                //   className="rounded-md"
                />
              </div>
            </div>
            <p className="text-sm text-gray-600 italic">
              Plot showing predicted (blue) vs actual (orange) energy generation over time
            </p>
          </div>

          <div className="flex flex-col items-center">
            <h3 className="text-lg font-semibold mb-4 text-blue-600">Feature Importance Visualization</h3>
            <div className="w-full max-w-2xl bg-gray-100 rounded-lg p-2 text-center mb-2">
              {/* Replace with your actual image path */}
            </div>
           
          </div>
        </div>

        <div className="bg-white p-6 rounded-xl shadow-lg">
          <h2 className="text-xl font-semibold mb-4 text-blue-700">Conclusions</h2>
          <ul className="list-disc pl-6">
            <li className="mb-2">
              The XGBoost model achieved high accuracy in predicting both DC and AC power output, with R² scores 
              above 0.94, indicating the model explains over 94% of the variance in energy generation.
            </li>
            <li className="mb-2">
              Global Horizontal Irradiance was the dominant predictor, as expected for solar energy generation, 
              but time of day and temperature also played significant roles.
            </li>
            <li className="mb-2">
              The model performs best during clear weather patterns and shows slightly reduced accuracy 
              during highly variable conditions.
            </li>
            <li className="mb-2">
              This predictive capability enables more accurate forecasting of solar energy production, 
              allowing for better grid integration and energy management.
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default ML;